#!/bin/bash
if [[ $1 = "redeploy" ]]; then
    docker tag sci-dict-client-i:latest sci-dict-client-old-i:latest
    docker tag sci-dict-be-i:latest sci-dict-be-old-i:latest

    docker-compose down
    docker-compose build
    docker-compose up -d
else 
    if [[ $1 = "rollback" ]]; then 
        docker tag sci-dict-client-old-i:latest sci-dict-client-i:latest
        docker image rm sci-dict-client-old-i
        docker tag sci-dict-be-old-i:latest sci-dict-be-i:latest
        docker image rm sci-dict-be-old-i

        docker-compose up
    else
        echo "Command should look like this: \n\n\t./deploy redeploy \n\nor like this \n\n\t./deploy rollback\n"
    fi
fi