### Increment public counter
PATCH http://localhost:5000/api/counters/i-was-here/inc

### Get counter
GET http://localhost:5000/api/counters/i-was-here

### List the whole dictionary
GET http://localhost:5000/api/dict

### Create new word
POST http://localhost:5000/api/dict/word
Content-Type: application/json

{
    "lt": "vaizduoklis", 
    "en": "monitor",
    "comments": "Damn, what a translation..."
}

### Create new word 2
POST http://localhost:5000/api/dict/word
Content-Type: application/json

{
    "lt": "sudėti", 
    "en": "",
    "comments": "Idk, can't find the translation..."
}

### Create new word (failing)
POST http://localhost:5000/api/dict/word
Content-Type: application/json

{
    "lt": "sudėti", 
    "en": "add",
    "comments": ""
}

### Update word with id=2
PUT http://localhost:5000/api/dict/word
Content-Type: application/json

{
    "id": 2,
    "lt": "sudėti", 
    "en": "to add",
    "comments": "Idk, can't find the translation."
}


### Delete word with id=11
DELETE http://localhost:5000/api/dict/word/11

### Create dict table and initialize
POST http://localhost:5000/api/dict/init