CREATE TABLE dict (
    id SERIAL, 
    lt VARCHAR(255), 
    en VARCHAR(255), 
    comments VARCHAR(255) NOT NULL, 
    PRIMARY KEY (id)
);
INSERT INTO dict(lt,en,comments) VALUES ('išvestinė','derivative','MPS');
INSERT INTO dict(lt,en,comments) VALUES ('tolydi','continuous','MPS');
INSERT INTO dict(lt,en,comments) VALUES ('tolygiai tolydi','uniformly continuous','MPS');
INSERT INTO dict(lt,en,comments) VALUES ('trūkiai (trūkio taškai)','Discontinuities (discontinuity points)','MPS');
INSERT INTO dict(lt,en,comments) VALUES ('Neišreikštinis išvestinės skaičiavimas','Implicit differentiation','MPS');
INSERT INTO dict(lt,en,comments) VALUES ('Dekarto','Cartesian','DM');
INSERT INTO dict(lt,en,comments) VALUES ('De Morgano','de Moivre’s','DM');
INSERT INTO dict(lt,en,comments) VALUES ('Deriniai','Combinations','10,12kl.');
INSERT INTO dict(lt,en,comments) VALUES ('Gretiniai','Permutations','10,12kl.');
INSERT INTO dict(lt,en,comments) VALUES ('Kėliniai','nPn permutations','10,12kl.');
INSERT INTO dict(lt,en,comments) VALUES ('matematinė viltis','expected value','12kl.');
INSERT INTO dict(lt,en,comments) VALUES ('dispersija','variance','12kl.');
INSERT INTO dict(lt,en,comments) VALUES ('vidutinis kvadratinis nuokrypis','Root-Mean-Square deviation (RMSD)','similar to standard deviation, 12kl., T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('standartinis nuokrypis','standard deviation','similar to RMSD, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('Sąryšis','Relation','DM');
INSERT INTO dict(lt,en,comments) VALUES ('(ne-)suderinta (lygčių sistema)','(in-)consistent','MPS');
INSERT INTO dict(lt,en,comments) VALUES ('Magnetinė indukcija','Magnetic flux density','12kl.fiz');
INSERT INTO dict(lt,en,comments) VALUES ('(ne-)apibrėžta (lygčių sistema)',NULL,'MPS');
INSERT INTO dict(lt,en,comments) VALUES ('Trikampio taisyklė (Matricos determinantas)','Rule of Sarrus','MPS');
INSERT INTO dict(lt,en,comments) VALUES ('Laplaso teorema','Laplace expansion','MPS');
INSERT INTO dict(lt,en,comments) VALUES ('Kontinuumo galia','Cardinality of the continuum','DM');
INSERT INTO dict(lt,en,comments) VALUES ('Kūnas','Field','MPS');
INSERT INTO dict(lt,en,comments) VALUES ('Negalimo trečiojo dėsnis','Law of excluded middle','DM');
INSERT INTO dict(lt,en,comments) VALUES ('Gretutiniai kampai','Angles on one side of a straight line','7kl');
INSERT INTO dict(lt,en,comments) VALUES ('sutvarkytas rinkinys','ordered tuple','DM');
INSERT INTO dict(lt,en,comments) VALUES ('Kėliniai','Permutation group (one-line notation)','MPS');
INSERT INTO dict(lt,en,comments) VALUES ('Keitiniai','Permutation group (two-line notation)','MPS');
INSERT INTO dict(lt,en,comments) VALUES ('Algoritmų teorija','Theory of computation','AT');
INSERT INTO dict(lt,en,comments) VALUES ('Matematinės logikos pradmenys','Boolean algebra','DM');
INSERT INTO dict(lt,en,comments) VALUES ('Prasilenkiančios tiesės','Skew lines','MPS');
INSERT INTO dict(lt,en,comments) VALUES ('mišrioji vektorių daugyba','triple scalar/box product','MPS');
INSERT INTO dict(lt,en,comments) VALUES ('skaliarinė vektorių daugyba','dot product','MPS, 11kl');
INSERT INTO dict(lt,en,comments) VALUES ('vektorinė vektorių daugyba','cross product','MPS');
INSERT INTO dict(lt,en,comments) VALUES ('koši-buniakovsio nelygybė','Cauchy-Schwarz-Buniakowsky inequality','MPS');
INSERT INTO dict(lt,en,comments) VALUES ('Kanoninės lygtys','Symmetric equations :DD','MPS');
INSERT INTO dict(lt,en,comments) VALUES ('Matricos rangas','matrix rank','related (?) to matrix column space, MPS, T.B.');
INSERT INTO dict(lt,en,comments) VALUES (NULL,'matrix column space','related (?) to matrix rank, MPS, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('egzistencinis kvantorius','existential quantifier','DM');
INSERT INTO dict(lt,en,comments) VALUES ('visuotinumo (bendrumo) kvantorius','universal quantifier','DM');
INSERT INTO dict(lt,en,comments) VALUES ('kirstinė','transversal','7kl, geometry, parallels');
INSERT INTO dict(lt,en,comments) VALUES ('kirstinė','secant','geometry, circle, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('atitinkamieji','corresponding','7kl, geometry, parallels');
INSERT INTO dict(lt,en,comments) VALUES ('priešiniai','alternate','7kl, geometry, parallels');
INSERT INTO dict(lt,en,comments) VALUES ('vienašaliai','consecutive','7kl, geometry, parallels');
INSERT INTO dict(lt,en,comments) VALUES ('kryžminiai','vertically opposite, vertical, opposite','7kl, geometry');
INSERT INTO dict(lt,en,comments) VALUES ('gretutiniai kampai','angles on one side of a straight line','7kl, geometry');
INSERT INTO dict(lt,en,comments) VALUES ('diferencialiniai ir integraliniai skaičiavimai','calculus','Real analysis, 12kl.');
INSERT INTO dict(lt,en,comments) VALUES ('eilutė; sekos suma','series','Real analysis, 11kl.');
INSERT INTO dict(lt,en,comments) VALUES ('sandauga','product','MPS');
INSERT INTO dict(lt,en,comments) VALUES (NULL,'decidable','AT');
INSERT INTO dict(lt,en,comments) VALUES ('apskaičiuojamas','computable','AT');
INSERT INTO dict(lt,en,comments) VALUES ('rodyklė','pointer','C language');
INSERT INTO dict(lt,en,comments) VALUES ('tiesių pluoštas','family of lines','Analytic geometry');
INSERT INTO dict(lt,en,comments) VALUES ('artinys',NULL,'11 klasė');
INSERT INTO dict(lt,en,comments) VALUES ('skaitmenys po kablelio','decimal places (d.p.)','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('reikšminiai skaitmenys','significant figures (s.f.)','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('lyginis','even','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('nelyginis','odd','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('teigiamas','positive','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('neigiamas','negative','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('sudėti','to add','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('atimti','to subtract','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('sudauginti','to multiply','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('(pa-)dalinti','to divide','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('sudėtis','addition','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('atimtis','subtraction','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('dalyba','division','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('dalus','divisible','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('daugyba','multiplication','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('skliaustai','brackets','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('sandauga','product','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('dalmuo','quotient','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('apibrėžti','define','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('apibrėžimas','definition','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('žymėti','denote','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('žymėjimas','notation',NULL);
INSERT INTO dict(lt,en,comments) VALUES (NULL,'hence','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES (NULL,'hence or otherwise','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('nupiešti eskizą','sketch','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES (NULL,'plot','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('skaidyti, atskliausti','expand','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('išraiška','expression','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('suprastinti','simplify','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('trupmena','fraction','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('skaitiklis','numerator','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('vardiklis','denominator','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('lygybė','equality','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('nelygybė','inequality','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('koordinačių plokštuma','coordinate plane / number plane / Cartesian plane','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('koordinačių plokštumos pradžia','origin','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('nežinomasis','unknown','Basic concepts, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('standartinė išraiška','scientific notation','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('išspręsti x atžvilgiu','solve for x','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('įsistatyti (į algebrinę išraišką)','substitute','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('kartotinis','multiple','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('mažiausias bendras kartotinis (MBK)','least common multiple (lcm)','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('daliklis','divisor','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('didžiausias bendras daliklis (DBD)','greatest common divisor (gcd)','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('lygties sprendiniai, šaknys','roots','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('išskirti kvadratą','to complete the square','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('pilnasis kvadratas','perfect square','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('skaidyti dauginamaisiais','factorise','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('trinaris','trinomial','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('daugianaris, polinomas','polynomial','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('daugiklis','factor','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('liekana','remainder','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('riba','limit','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('atžvilgiu','respect','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('baigtinis','finite','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('begalinis','infinite','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('seka','sequence','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('(sekos) narys, elementas','term (of a sequence)','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('eilutė','series','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('aritmetinė progresija','arithmeetic sequence (arithmetic progression)','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('aritmetinės progresijos skirtumas','common difference','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('geometrinė progresija','geometric sequence (geometric progression)','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('geometrinės progresijos vardiklis','common ration','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('logaritmas','logarithm','Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('aibė','set','Set Algebra, T.B., 11kl.');
INSERT INTO dict(lt,en,comments) VALUES ('sankirta','intersection','Set Algebra, T.B., 11kl.');
INSERT INTO dict(lt,en,comments) VALUES ('sąjunga','union','Set Algebra, T.B., 11kl.');
INSERT INTO dict(lt,en,comments) VALUES ('papildinys','complement','Set Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('aibių atimtis, skirtumas','relative complement, set difference','Set Algebra, T.B., 11kl.');
INSERT INTO dict(lt,en,comments) VALUES ('tuščioji aibė','the empty (null) set','Set Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('matrica','matrix','Matrix Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('vienetinė matrica','identity matrix','Matrix Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('nulinė matrica','zero matrix','Matrix Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('kvadratinė matrica','square matrix','Matrix Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('atvirkštinė matrica','inverse matrix','Matrix Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('determinantas','determinant','Matrix Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('papildyta matrica','augmented matrix','Matrix Algebra, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('trūkio taškas','point of discontinuity','Functions, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('tiesinė lygtis','linear equation','Functions, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('apibrėžimo sritis','domain','Functions, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('reikšmių sritis','range','Functions, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('sudėtinė (funkcija)','composite','Functions, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('atvirkštinė (funkcija)','inverse (function)','Functions, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('susikirtimas su x ašimi','x-intercept','Functions, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('lygiagretus','parallel','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('status, statmenas','perpendicular','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('posvyris, krypties koeficientas','gradient (slope)','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('viršūnė','vertex','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('statusis trikampis','right-angled triangle','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('lygiašonis trikampis','isosceles triangle','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('lygiakraštis trikampis','equilateral triangle','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('lygūs trikampiai','congruent triangles','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('keturkampis','quadrilateral','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('stačiakampis','rectangle (rectangular)','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('lygiagretainis','parallelogram','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('rombas','rhombus','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('trapecija','trapezium','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('kraštinė','side','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('įžambinė','hypotenuse','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('pusiaukampinė','bisetor','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('pasviroji','oblique','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('aukštinė','altitude','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('(tiesės) susikertančios viename taške','concurrent','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('kirstinė','secant','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('lankas','arc','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('įbrėžtinis kampas','inscribed angle','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('centrinis kampas','central angle','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('kampas prieš apskritimo lanką AB','angle subtending arc AB','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('skritulio nuopjova / linijos atkarpa','segment','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('išpjova','sector','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('styga','chord','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('kirstinė','transversal line','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('gretutiniai kampai','supplementary angles (??)','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('vidaus priešiniai','alternate interior','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('išorės priešiniai','alternate exterior','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('vidaus vienašaliai','allied, co-interior','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('išorės vienašaliai','co-exterior','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('spindulys, dalijantis kampą pusiau','angle bisector','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES (NULL,'angle of depression','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES (NULL,'angle of elevation','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('plotas','area','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('tūris','volume','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('pagrindas','base','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('daugiakampis','polygon','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('taisyklingasis daugiakampis','regular polygon','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('taisyklingoji piramidė','regular pyramid','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('piramidės viršūė, kūgio viršūnė, lygiašonio trikampio viršūnė kur susikera lygios kraštinės','apex','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('gretasieis','parallelpiped','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('stačiakampis gretasienis','cuboid','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('ritinys, cilindras','cylinder','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('kūgis','cone','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('rutulys, sfera','sphere','Geometry, T.B.');
INSERT INTO dict(lt,en,comments) VALUES ('svyravimas','oscillation','Mechaniniai svyravimai ir bangos 8 kl., fiz');
INSERT INTO dict(lt,en,comments) VALUES ('švytuoklė','pendulum','Mechaniniai svyravimai ir bangos 8 kl., fiz');
INSERT INTO dict(lt,en,comments) VALUES ('banga','wave','Mechaniniai svyravimai ir bangos 8 kl., fiz');
INSERT INTO dict(lt,en,comments) VALUES ('skersinė','transverse','Mechaniniai svyravimai ir bangos 8 kl., fiz');
INSERT INTO dict(lt,en,comments) VALUES ('išilginė','longitudinal','Mechaniniai svyravimai ir bangos 8 kl., fiz');
INSERT INTO dict(lt,en,comments) VALUES ('slopinamasis','damped','Mechaniniai svyravimai ir bangos 8 kl., fiz');
INSERT INTO dict(lt,en,comments) VALUES ('bangos ilgis','wavelenght','Mechaniniai svyravimai ir bangos 8 kl., fiz');
INSERT INTO dict(lt,en,comments) VALUES ('atstumas','distance','Mechaniniai svyravimai ir bangos 8 kl., fiz');
INSERT INTO dict(lt,en,comments) VALUES ('poslinkis','displacement','Mechaniniai svyravimai ir bangos 8 kl., fiz');
INSERT INTO dict(lt,en,comments) VALUES ('dažnis','frequency','Mechaniniai svyravimai ir bangos 8 kl., fiz');
INSERT INTO dict(lt,en,comments) VALUES ('amplitudė','amplitude','Mechaniniai svyravimai ir bangos 8 kl., fiz');
INSERT INTO dict(lt,en,comments) VALUES ('periodas','period','Mechaniniai svyravimai ir bangos 8 kl., fiz');
INSERT INTO dict(lt,en,comments) VALUES ('greitis','velocity','Mechaniniai svyravimai ir bangos 8 kl., fiz');
INSERT INTO dict(lt,en,comments) VALUES ('kinetinė energija','kinetic energy','Mechaniniai svyravimai ir bangos 8 kl., fiz');
INSERT INTO dict(lt,en,comments) VALUES ('potencinė energija','potential energy','Mechaniniai svyravimai ir bangos 8 kl., fiz');
INSERT INTO dict(lt,en,comments) VALUES ('rezonansas','resonance','Mechaniniai svyravimai ir bangos 8 kl., fiz');
INSERT INTO dict(lt,en,comments) VALUES ('sklidimas','propagation','Mechaniniai svyravimai ir bangos 8 kl., fiz');
INSERT INTO dict(lt,en,comments) VALUES ('tekstiniai uždaviniai','word problems',NULL);
INSERT INTO dict(lt,en,comments) VALUES ('procentinis didėjimas','percent increase, percent change','10kl. procentai');
INSERT INTO dict(lt,en,comments) VALUES ('procentinis mažėjimas','percent decrease, percent change','10kl. procentai');
INSERT INTO dict(lt,en,comments) VALUES ('palūkanos','interest','10kl. procentai');
INSERT INTO dict(lt,en,comments) VALUES ('palūkanų norma','interest rate','10kl. procentai');
INSERT INTO dict(lt,en,comments) VALUES ('sudėtinės palūkanos','compound interest','10kl. procentai');
INSERT INTO dict(lt,en,comments) VALUES ('paprastosios palūkanos','simple interest','10kl. procentai');
INSERT INTO dict(lt,en,comments) VALUES ('paskola','loan','10kl. procentai');
INSERT INTO dict(lt,en,comments) VALUES ('modulis','absolute value (abs)','11kl.');